import type { Tasks } from "@/modules/task/schema";

export const initialDataTasks: Tasks = [
  // === TODO ===
  {
    id: 1,
    title: "Belajar Tailwind",
    description: "Mempelajari dasar-dasar Tailwind CSSa",
    status: "todo",
    priority: "high",
    dueDate: new Date("2025-11-01"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    title: "Membuat Komponen Button",
    description: "Implementasi button dengan variasi style Tailwind",
    status: "todo",
    priority: "medium",
    dueDate: new Date("2025-12-03"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    title: "Riset UI Library",
    description: "Membandingkan beberapa UI library untuk project",
    status: "todo",
    priority: "low",
    dueDate: new Date("2025-12-04"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    title: "Belajar Routing",
    description: "Mempelajari dasar routing di React/Next.js",
    status: "todo",
    priority: "high",
    dueDate: new Date("2025-12-05"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    title: "Setup GitHub Actions",
    description: "Menyiapkan CI/CD sederhana untuk project",
    status: "todo",
    priority: "medium",
    dueDate: new Date("2025-12-06"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // === INPROGRESS ===
  {
    id: 6,
    title: "Membuat Dashboard",
    description: "Membuat halaman dashboard dengan form dan list task",
    status: "inprogress",
    priority: "medium",
    dueDate: new Date("2025-12-02"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    title: "Integrasi API",
    description: "Menghubungkan frontend dengan API backend",
    status: "inprogress",
    priority: "high",
    dueDate: new Date("2025-12-03"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    title: "Membuat Form Validasi",
    description: "Menambahkan validasi pada form input",
    status: "inprogress",
    priority: "medium",
    dueDate: new Date("2025-12-04"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    title: "Desain Layout Responsive",
    description: "Membuat layout agar responsive di berbagai device",
    status: "inprogress",
    priority: "high",
    dueDate: new Date("2025-12-05"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    title: "Implementasi Dark Mode",
    description: "Menambahkan fitur dark mode pada aplikasi",
    status: "inprogress",
    priority: "low",
    dueDate: new Date("2025-12-06"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // === DONE ===
  {
    id: 11,
    title: "Setup Projectt",
    description: "Inisialisasi project dengan Tailwind dan konfigurasi dasar",
    status: "done",
    priority: "low",
    dueDate: new Date("2025-11-28"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    title: "Install Dependencies",
    description: "Menginstall library yang dibutuhkan untuk project",
    status: "done",
    priority: "medium",
    dueDate: new Date("2025-11-28"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    title: "Konfigurasi ESLint",
    description: "Menambahkan konfigurasi linting untuk menjaga kualitas kode",
    status: "done",
    priority: "low",
    dueDate: new Date("2025-11-28"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    title: "Setup Prettier",
    description: "Menambahkan formatter otomatis untuk konsistensi kode",
    status: "done",
    priority: "low",
    dueDate: new Date("2025-11-27T12:00:00Z"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    title: "Membuat Readme",
    description: "Menulis dokumentasi awal project di README.md",
    status: "done",
    priority: "medium",
    dueDate: new Date("2025-11-28"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
